# Converts a 16-bit PCM WAV file into a C header with 12-bit DAC-formatted audio samples
# Script generated by ChatGPT

import wave
import numpy as np
from textwrap import wrap

INPUT_WAV  = "sfx_hit.wav"   # .wav file
OUTPUT_H   = "hit_sound.h"   # header file to generate
ARRAY_NAME = "hit_sfx_data"  # C array name
DAC_CONFIG = 0x3000          # 0b0011_0000_0000_0000 for MCP4822-style DAC

with wave.open(INPUT_WAV, "rb") as wf:
    n_channels = wf.getnchannels()
    sampwidth  = wf.getsampwidth()
    framerate  = wf.getframerate()
    n_frames   = wf.getnframes()

    print(f"channels: {n_channels}, width: {sampwidth} bytes, fs: {framerate} Hz, frames: {n_frames}")

    if sampwidth != 2:
        raise ValueError("Expected 16-bit PCM (2 bytes per sample).")

    raw = wf.readframes(n_frames)
    samples = np.frombuffer(raw, dtype=np.int16)

    if n_channels == 2:
        samples = samples[::2]

# Map signed 16-bit (-32768..32767) to 12-bit unsigned (0..4095)
# First map to 0..65535, then scale to 0..4095
samples_32 = samples.astype(np.int32)
samples_u16 = ((samples_32 + 32768) * 4095 // 65535).astype(np.uint16)

# Mask to 12 bits and OR with DAC config
dac_words = (samples_u16 & 0x0FFF) | DAC_CONFIG

length = len(dac_words)

# Generate C header text
header_lines = []
header_lines.append("#ifndef HIT_SOUND_H")
header_lines.append("#define HIT_SOUND_H")
header_lines.append("")
header_lines.append("#include <stdint.h>")
header_lines.append("")
header_lines.append(f"#define HIT_SFX_LEN {length}")
header_lines.append(f"static const uint16_t {ARRAY_NAME}[HIT_SFX_LEN] = {{")

# Format as hex, 8 values per line
hex_vals = [f"0x{val:04X}" for val in dac_words]
for line in wrap(", ".join(hex_vals), 80):
    header_lines.append("    " + line)

header_lines.append("};")
header_lines.append("")
header_lines.append("#endif // HIT_SOUND_H")

with open(OUTPUT_H, "w") as f:
    f.write("\n".join(header_lines))

print(f"Wrote header: {OUTPUT_H} with {length} samples.")
